INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'678');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Abel Albino');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Adolfo Rodriguez Saa');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Adrian Paenza');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Aecio Neves');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'AFSCA');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Agustin Rossi');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Albert Einstein');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Alberto Fernandez');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Alberto Perez');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Alberto Rodriguez Saa');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Alberto Sileoni');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Alcira Argumedo');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Alejandra Gils Carbo');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Alejandro Arlia');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Alejandro Tullio');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Alemania');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Alfonso Prat Gay');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Alfredo Scoccimarro');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Alicia Kirchner');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Alieto Guadagni');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Amado Boudou');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ana Maria Edwin');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ángela Merkel');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Anibal Fernandez');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Antonio Bonfatti');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Antonio Marino');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Argentina');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Artemio Lopez');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Arturo Puricelli');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Augusto Costa');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Axel Kicillof');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Barack Obama');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Beatriz Sarlo');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Belgica');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Bosnia');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Carlos Heller');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Carlos Kunkel');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Carlos Pagni');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Carlos Reutemann');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Carlos Tomada');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Cesar Milani');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Claudio Belocopitt');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Claudio Lozano');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Conferencia Episcopal Argentina');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Cristian Ritondo');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Cristina Fernandez de Kirchner');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Daniel Filmus');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Daniel Hadad');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Daniel Peralta');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Daniel Reposo');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Daniel Scioli');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Danilo Astori');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Dario Giustozzi');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Debora Giorgi');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Diego Bossio');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Diego Santilli');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Dilma Rousseff');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Domingo Cavallo');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Eduardo Amadeo');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Eduardo Costantini');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Eduardo Duhalde');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'El Cronista');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Elena Highton de Nolasco');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Elisa Carrio');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ernesto Sanz');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Esteban Bullrich');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Esteban Righi');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Eugenio Zaffaroni');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Facundo Moyano');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Federico Pinedo');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Federico Sturzenegger');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Felipe Sola');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Felix Diaz');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Fernanda Reyes');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Fernando de la Rua');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Fernando Iglesias');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Fernando Lugo');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Fernando Navarro');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Fernando Solanas');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Florencia Saintout');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Florencio Randazzo');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Francisco de Narvaez');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Franco Macri');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Francois Hollande');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Gabriel Mariotto');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Gabriela Cerruti');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Gabriela Michetti');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Gerardo Morales');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Geronimo Venegas');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Gerry Garbulsky');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Gilberto Alegre');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Gildo Insfran');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Grupo Clarin');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Guillermo Montenegro');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Guillermo Pereyra');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Gustavo Ferrari');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Hector Recalde');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Hector Timerman');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Hermes Binner');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Hernan Lombardi');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Horacio Rodriguez Larreta');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Horacio Verbitsky');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Hugo Biolcati');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Hugo Chavez');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Hugo Moyano');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Hugo Yasky');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ider Peretti');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Iglesia Catolica');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Iran');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ivan Petrella');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Javier Gonzalez Fraga');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jorge Altamira');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jorge Argüello');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jorge Bergoglio');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jorge Capitanich');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jorge Di Lello');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jorge Lanata');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jorge Lemus');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jorge Macri');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jorge Sapag');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jorge Taiana');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jose Alperovich');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jose Ignacio de Mendiguren');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jose Luis Gioja');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jose Manuel de la Sota');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jose Maria Campagnoli');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jose Pedraza');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Jose Sbatella');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Juan Cabandie');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Juan Carr');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Juan Goya');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Juan Jose Aranguren');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Juan Jose Campanella');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Juan Jose Llach');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Juan Jose Mussi');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Juan Manuel Abal Medina');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Juan Manuel Urtubey');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Juan Pablo Schiavi');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Julian Assange');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Julian Dindart');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Julian Dominguez');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Juliana Di Tullio');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Julio Alak');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Julio Cobos');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Julio De Vido');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Julio Pereyra');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Julio Piumato');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'La Nacion');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Leandro Despouy');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Leon Arslanian');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Lucia Corpacci');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Luis D Elia');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Luis Juez');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Luis Majul');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Luis Miguel Etchevehere');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Luis Naidenoff');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Luis Zamora');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Lula da Silva');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Marcelo Meis');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Marcelo Rubinstein');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Marcelo Stubrin');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Marcelo Tinelli');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Marcos Aguinis');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Margarita Stolbizer');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Maria Eugenia Estenssoro');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Maria Eugenia Vidal');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Mariano Grondona');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Mariano Rajoy');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Mariano Recalde');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Marina Silva');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Mario Das Neves');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Mario Ishii');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Mario Pergolini');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Martin Caparros');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Martin Insaurralde');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Martin Lousteau');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Martin Redrado');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Martin Sabbatella');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Maurice Closs');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Mauricio Macri');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Mempo Giardinelli');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Mercedes Marco del Pont');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Miguel Del Sel');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Miguel Galuccio');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Miguel Pesce');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Miguel Pichetto');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ministerio de Industria');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Mitt Romney');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Muamar Khadafi');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Nestor Kirchner');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Nicolas Sarkozy');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Nilda Garre');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Nora De Lucia');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Norberto Oyarbide');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Norberto Yauhar');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Oscar Aguad');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Oscar Parrilli');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Pablo Micheli');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Pagina 12');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Rafael Bielsa');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Rafael Di Zeo');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Revista Fortuna');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ricardo Alfonsin');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ricardo Casal');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ricardo Colombi');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ricardo Darin');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ricardo Echegaray');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ricardo Gil Lavedra');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ricardo Jaime');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ricardo Lorenzetti');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ricardo Pignanelli');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Roberto Baradel');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Roberto Feletti');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Roberto Lavagna');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Roberto Pianelli');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Rogelio Frigerio');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ruben Giustiniani');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Ruben Sobrero');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Sebastian Piñera');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Sergio Bergman');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Sergio Berni');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Sergio Massa');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Silvina Batakis');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Sonia Escudero');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Suiza');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Tiempo Argentino');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Victor de Gennaro');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Victor Hugo Morales');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Victoria Donda');
INSERT INTO Entity (type, created_by, created, name) VALUES (1,0, now(),'Vilma Ibarra');
